import { Header } from "@/src/app/components/Header";
import { Providers } from "@/src/app/layouts/Providers";
import "@/src/app/styles/globals.css";
import { getServerSessionData } from "@/src/entities/main";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getServerSessionData();
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <Providers>
          <Header user={user} />
          {children}
        </Providers>
      </body>
    </html>
  );
}

