import "@/src/app/styles/globals.css";
import { antTheme } from "@/src/app/styles/theme";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <AntdRegistry>
          <ConfigProvider theme={antTheme}>{children}</ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}

